language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/topups_test

node_js:  
  - 12

before_script:
  - psql -c 'create database  topups_test;' -U postgres
  - psql -U postgres -d topups_test -a -f sql/db.sql


services:
  - postgresql
